### ISSUE TITLE
[Enh] add product history in "add product" dialogue to ease/quicken list creation

### ISSUE THREAD

**Issue by scheunengeist** [prellele/shoppinglist-android#5]
System used:
Android 4.0.4 on a Sony Ericsson Xperia Ray
Shoppinglist: (present version from Google Play) 2.0(?)

Issue:
When adding products to a list, I have to write out the product's name each time, regardless whether the product has been used before or is already listed in another list.

Suggested Improvement:
Remember products that have already been entered before and present them in a list, e. g. after 2 or 3 letters have been provided.

Expected Result:
Create shopping lists more quickly and without having to type much, while still keeping the products separate from amount and unit.

Praise:
Thanks for this really cool shopping list app! It is pretty much exactly what I'm looking for, except for the feature described above. I'm presently using Trolly, which can't really handle amounts or units, but makes it easy to add items by remembering everything I enter.  So now I can only hope that your very nice software is still being worked on. :)

Thank you for your time!

**Comment by prellele** [comment]
Thanks for the suggestion - I like this idea! 
Looking forward to some more sparetime :tm: to implement this

**Comment by prellele** [comment]
I've released it in play store - have fun :)

**Comment by scheunengeist** [comment]
Works nicely! Thanks for implementing!
This is now my shopping list app of choice. :)
