### ISSUE TITLE
keyboard input not transferred to apps after using Shoppinglist

### ISSUE THREAD

**Issue by scheunengeist** [prellele/shoppinglist-android#7]
System used:
Android 4.0.4 on a Sony Ericsson Xperia Ray
Shoppinglist: (present version from Google Play) 1.3(?)

Issue:
Sometimes when using Shoppinglist, the soft keyboard, while still showing up and accepting input, will not transfer the input to the app any longer. This behaviour lasts on also after closing Shoppinglist, i. e. other apps are affected as well.
Other UI elements seem unaffected and work as expected.
Rebooting the phone restores normal behaviour.

Research so far:
- A search for this behaviour connected with either Android 4.0.4 or the Xperia Ray came up empty. It's possible though that I didn't look for the right terms and/or in the right places.
- Using an alternative soft keyboard (Hacker's Keyboard) instead of the stock Xperia keyboard doesn't seem to solve the issue.
- The problem seems only to occur when using Shoppinglist, not with any other app on my phone. However, I couldn't find a reproduction procedure so far. First time I noticed this, I was editing shops iirc, last time I was merely looking at a shop-specific item list. I usually leave the app by pressing the home button.

Thanks in advance!

Update: [Reproduction and Workaround](https://github.com/prellele/shoppinglist-android/issues/7#issuecomment-37753264)

**Comment by prellele** [comment]
I will have a look into it. Let's see if I could reproduce it or not. 

Please inform me, if you have further information.

**Comment by prellele** [comment]
Although I was able to organize a Xperia devise, I can't reproduce this.
As long as this is not reproducable or verifiable, I close it. 

Feel free to reopen or comment if you could provide more information.

**Comment by scheunengeist** [comment]
I played around with it over the last weeks. It seems I can now reproduce the behaviour and have even found a workaround.

Reproduction on my device:
1. Launch Shoppinglist
2. Wait for display to dim and then go off completely
3. Reactivate display by pressing (hardware) home button (returning to Shoppinglist)
4. Leave Shoppinglist by pressing (hardware) home button
=> From now on, text is not transferred any longer from the keyboard to the input field, e. g. in SMS application or note taking app etc.
At this point, I used to have to reboot my phone, until I found the following:

Workaround:
1. With "stalled" keyboard, launch Shoppinglist again
2. Press back button to leave app (possibly pressing it several times to leave market-specific list first)
=> keyboard can be used normally again

**Comment by prellele** [comment]
Surely this was pretty annoying for you, so I'm glad to here you have found a workaround for this.
I will try to reproduce this, with help of the new information you provided.

**Comment by prellele** [comment]
I can't reproduce this on Stock Android 4.3.0. As I have no Sony or Xperia device available, I won't be able to fix this, sorry.

**Comment by scheunengeist** [comment]
I understand. It's hard to find a bug you can't replicate. :)
Anyway, the workaround turned out to be quite unreliable, and even if I ventured to install (e. g.) CyanogenMod on my phone, I'd still be stuck with a 4.0.x version of Android for my particular device.
In any event, thanks for the time you invested!
