### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by keong17** [prellele/shoppinglist-android#8]
It is a good app.

There are some issues.
- there is problem with Google Drive export and import. export was successful, but there is no file found in my Google Drive. So I cannot import the exported shoppinglist.
- spelling mistake for the word "emport". It should be "import".
- there are language that I did not understand in the history section. I guessed it was German. Can you change to English?

Thank you for making this app.

**Comment by prellele** [comment]
Hi,
thanks for reporting this. Please avoid summing multiple issues in one in the future. See [here](https://github.com/prellele/shoppinglist-android/blob/master/CONTRIBUTING.md#bug-reports).

> there is problem with Google Drive export and import. export was successful, but there is no file found in my Google Drive. So I cannot import the exported shoppinglist.

I'll have a look into the export function.

> spelling mistake for the word "emport". It should be "import".

I've fixed it here: b7d44d5443055b918c83e138a624746a080d9f10

> there are language that I did not understand in the history section

Where is this exactly? Could you provide more information or a screenshot?

Cheers,
prellele

**Comment by prellele** [comment]
I opened a new issue for the Google Drive bug you are facing. #9
